{% set version = "0.8.0" %}

package:
  name: mangohud
  version: {{ version }}

source:
  url: https://github.com/flightlessmango/MangoHud/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 80cade0db0b8837bddab1cbb47078026771e6fb9994c1edf93cfe6aa31b3ee47
  patches:
    # https://github.com/conda-forge/staged-recipes/pull/27526#issuecomment-2340403320
    - conda-forge-xdg-data_dirs.patch
    # Without this flag, it is too easy to freeze on vulkan apps
    # https://github.com/flightlessmango/MangoHud/issues/1354
    - flag_for_disable_preload.patch

build:
  number: 0
  # No support for osx https://github.com/flightlessmango/MangoHud/issues/1425
  skip: true  # [osx]
  # I'm having trouble with windows and finding python-mako
  # An other maintainer will have to jump in to help
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - meson
    - ninja
    - cmake
    - pkg-config
    - glslang
    # python-mako and mako are needed at build time
    - python 3.12
    - mako
  host:
    - nlohmann_json
    - spdlog
    - fmt
    # implot is not available on conda-forge
    # https://github.com/conda-forge/staged-recipes/issues/27528
    # - implot
    # - imgui
    - wayland          # [linux]
    - libgl-devel      # [linux]
    - libegl-devel     # [linux]
    - xorg-libx11      # [linux]
    - libxkbcommon     # [linux]

test:
  commands:
    - mangohud --version
    - mangohud echo hi  # [unix]
    - where mangohud    # [win]

about:
  home: https://github.com/flightlessmango/MangoHud
  summary: A Vulkan and OpenGL overlay for monitoring FPS, temperatures, CPU/GPU load and more.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
